name: Keep Render App Alive

on:
  schedule:
    - cron: "* * * * *"   # runs every minute (maximum allowed)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App twice
        run: |
          curl -s -o /dev/null https://bike-showroom-management-new.onrender.com/
          sleep 5
          curl -s -o /dev/null https://bike-showroom-management-new.onrender.com/
