name: Keep Render App Alive

on:
  schedule:
    - cron: "* * * * *"   # runs every minute
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App twice
        run: |
          echo "ðŸ”” First ping started"
          curl -s -o /dev/null https://bike-showroom-management-new.onrender.com/
          echo "âœ… First ping done"

          sleep 5

          echo "ðŸ”” Second ping started"
          curl -s -o /dev/null https://bike-showroom-management-new.onrender.com/
          echo "âœ… Second ping done"

          echo "ðŸš€ Render app is alive"
